name: Artifacts
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: mkdir -p test
    - run: echo hello > test/world.txt
    - uses: actions/upload-artifact@v1
      with:
        name: test
        path: test/world.txt
